### ISSUE TITLE
Final keyword used throughout on class definitions

### ISSUE THREAD

**Issue by chickenland** [opengento/magento2-gdpr#96]
## Description  
The extension fails ECG/M2 coding standards and becomes exceedingly hard to extend as it includes the FINAL keyword against a large number of classes.  These should be removed to allow for 1) Coding standards compliance and 2) allow for extension of the module.

**Steps to reproduce the behavior**
`./vendor/bin/phpcs --standard=Magento2 app/code/Opengento/Gdpr/`

**Comment by thomas-kl1** [comment]
Magento 2 standards bans "final" keywords because Magento lacks of extension points. If you feel that the module miss of extension points, feel free to raise an issue with guidance of what you are trying to achieve, I'll be glad to help you and point you to the right way.

As a remainder, if you need to override a final class, you can implement parents of the targeted class and inject it into composition if you need to fetch back some methods.

**Comment by thomas-kl1** [comment]
Removing the bug label as it's not a bug, but a feedback

**Comment by thomas-kl1** [comment]
@chickenland would you explain what was blocking you?
